chore: adding typescript user creation for ionos
chore: adding typescript user creation for ionos

chore: adding typescript user creation for ionos

chore: adding typescript user creation for ionos

diff --git a/.github/workflows/ionos-cp-workflow.yml b/.github/workflows/ionos-cp-workflow.yml
--- a/.github/workflows/ionos-cp-workflow.yml
+++ b/.github/workflows/ionos-cp-workflow.yml
@@ -29,80 +29,23 @@ jobs:
               }
             ]
 
+      - name: Set up Node.js
+        uses: actions/setup-node@v4
+        with:
+          node-version: 20
+
+
       - name: IONOS User Creation
         id: create-ionos-user
+        working-directory: kit/ionos/buildingblocks/vdc-users/buildingblock
         env:
-          TOKEN_IONOS: ${{ secrets.TOKEN_IONOS }}
-          IONOS_FIRST_LOGIN_PW: ${{ secrets.IONOS_FIRST_LOGIN_PW }}
+          IONOS_USERNAME: ${{ secrets.IONOS_USERNAME }}
+          IONOS_PASSWORD: ${{ secrets.IONOS_PASSWORD }}
           MESH_USERS: ${{ steps.setup-meshstack-auth.outputs.users }}
         run: |
-          #!/bin/bash
-
-          # Enable best practices for error handling and debugging
-          set -o errexit  # Exit the script when any command fails
-          set -o errtrace # Trace errors in functions
-          set -o pipefail # Set the exit status of a pipe to the one that fails
-          set -o nounset  # Exit the script when using an undefined variable
-
-          # API credentials
-          url="https://api.ionos.com/cloudapi/v6/um/users"
-
-          # Pagination parameters
-          limit=100
-          offset=0
-
-          # Extract list of user emails from MESH_USERS environment variable
-          users_list="$(echo "$MESH_USERS" | jq '.[].email')"
-
-          # Create new users from the MESH_USERS list
-           for user in $(echo "$MESH_USERS" | jq -c '.[]'); do
-            email="$(echo "$user" | jq -r '.email')"
-            firstname="$(echo "$user" | jq -r '.firstName')"
-            lastname="$(echo "$user" | jq -r '.lastName')"
-            echo "User $email  Creating..."
-            password=$IONOS_FIRST_LOGIN_PW
-
-              # Prepare payload for creating the user
-              new_user_payload="{\"properties\": {\"firstname\": \"$firstname\", \"lastname\": \"$lastname\", \"email\": \"$email\", \"administrator\": false, \"password\": \"$password\", \"active\": true}}"
-
-              # Make the POST request to create the user
-              create_response="$(curl -s -w "%{http_code}" -X POST -H "Authorization: Basic $TOKEN_IONOS" -H "Content-Type: application/json" -d "$new_user_payload" "$url")"
-              http_code=$(echo "$create_response" | tail -n 1)
-              response_body=$(echo "$create_response" | sed '$d')
-
-              # Output HTTP status code and response body for debugging
-              echo "HTTP Status Code: $http_code"
-              echo "Response: $response_body"
-
-              # If user creation is successful (HTTP 202), check the activation status
-              if [ "$http_code" -eq 202 ]; then
-                echo "User $email created successfully, checking activation status..."
-                user_id=$(echo "$response_body" | jq -r '.id')
-                attempts=0
-                max_attempts=5
-
-                # Retry checking user activation status a few times
-                while [ $attempts -lt $max_attempts ]; do
-                  user_status=$(curl -s -H "Authorization: Basic $TOKEN_IONOS" "$url/$user_id" | jq -r '.properties.active')
-                  if [ "$user_status" == "true" ]; then
-                    echo "User $email successfully activated."
-                    break
-                  else
-                    echo "User $email is not yet activated, retrying in 10 seconds..."
-                    sleep 10
-                    attempts=$((attempts + 1))
-                  fi
-                done
-
-                # If activation fails after max attempts, notify the user
-                if [ $attempts -eq $max_attempts ]; then
-                  echo "User $email could not be activated, maximum attempts reached."
-                fi
-              else
-                # If user creation fails, output the status code
-                echo "Error creating user $email. Status code: $http_code"
-              fi
-          done
+          npm i --save @ionos-cloud/sdk-nodejs
+          set -e  # Fail on error
+          node index.ts
 
       - name: Send status
         if: ${{ steps.create-ionos-user.outcome == 'success' || steps.create-ionos-user.outcome == 'failure' }}
